Copy code
name: Deploy to EC2 with Nginx

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE }}
        source: build/
        target: /var/www/react-app/

    - name: SSH into EC2 and configure Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE }}
        script: |
          sudo apt-get -y update
          sudo apt-get install -y nginx
          sudo rm /etc/nginx/sites-enabled/default
          sudo cp /var/www/react-app/nginx.conf /etc/nginx/sites-available/react-app
          sudo ln -s /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/react-app
          sudo systemctl restart nginx
