Copy code
name: Deploy to EC2 with Nginx

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE }}
        source: build/
        target: /var/www/react-app/

    - name: SSH into EC2 and configure Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE }}
        script: |
          sudo apt-get -y update
          sudo apt-get install -y nginx
          sudo rm /etc/nginx/sites-enabled/default
          sudo cp /var/www/react-app/nginx.conf /etc/nginx/sites-available/react-app
          sudo ln -s /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/react-app
          sudo systemctl restart nginx
